apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: policy-openshift-logging-forwarder-placement
  namespace: acm-policies
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: acm-lab
              operator: In
              values:
                - logging
  clusterSets:
    - default
